service: my-express-application
package:
  excludeDevDependencies: false
custom:
  serverless-offline:
    port: ${file(${opt:config, 'dev'}.yml):PORT}
plugins:
  - serverless-plugin-typescript
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:config, 'dev'}
  environment:
    PROJECT_ID: ${file(${opt:config, 'dev'}.yml):PROJECT_ID}
    PORT: ${file(${opt:config, 'dev'}.yml):PORT}
    BASE_URL: ${file(${opt:config, 'dev'}.yml):BASE_URL}
    PAGES: ${file(${opt:config, 'dev'}.yml):PAGES}
    SEARCH_INDEX: ${file(${opt:config, 'dev'}.yml):SEARCH_INDEX}
    ELASTIC_URI: ${file(${opt:config, 'dev'}.yml):ELASTIC_URI}
functions:
  getNavigation:
    handler: ${file(${opt:config, 'dev'}.yml):CONTROLLER_PATH}.getNavigation
    events:
      - http:
          path: get_menu
          method: get
  getFooter:
    handler: ${file(${opt:config, 'dev'}.yml):CONTROLLER_PATH}.getFooter
    events:
      - http:
          path: get_footer
          method: get
  getHomeLayout:
    handler: ${file(${opt:config, 'dev'}.yml):CONTROLLER_PATH}.getHomeLayout
    events:
      - http:
          path: get_home
          method: post
  getResource:
    handler: ${file(${opt:config, 'dev'}.yml):CONTROLLER_PATH}.getResource
    events:
      - http:
          path: get_resource
          method: post
  getStaticPage:
    handler: ${file(${opt:config, 'dev'}.yml):CONTROLLER_PATH}.getStaticPage
    events:
      - http:
          path: get_static/{slug}
          method: get
  getTranslation:
    handler: ${file(${opt:config, 'dev'}.yml):CONTROLLER_PATH}.getTranslation
    events:
      - http:
          path: get_translation/{lang}
          method: get
  search:
    handler: ${file(${opt:config, 'dev'}.yml):CONTROLLER_PATH}.search
    events:
      - http:
          path: search/{type}
          method: post
